name: Merge to Main

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "93549755+PipoAT@users.noreply.github.com"
          git config --global user.name "Andrew Pipo"

      - name: Merge to Main
        run: |
          git checkout main
          git merge --no-ff dev
          git push origin main
